<a href="https://colab.research.google.com/github/srajme25-code/cloud_lab/blob/main/lab1_and_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
"""
Name    : Siddharatha Raj
Program : Matrix Operations using Python
Purpose : Cloud Computing Lab Assignment
"""

import random
import numpy as np
from collections import defaultdict

# ----------------------------------------------------
# 1. CREATE DATA FILE (20000 x 10000) USING RANDOM
# ----------------------------------------------------

def create_large_data_file(filename="matrix_data.txt",
                           rows=20000,
                           cols=10000,
                           chunk_size=100):
    """
    Creates a large matrix file using random generator parameters
    Data is written in chunks to avoid memory crash
    """
    with open(filename, "w") as f:
        for _ in range(rows // chunk_size):
            chunk = np.random.randint(
                low=0,
                high=100,
                size=(chunk_size, cols)
            )
            np.savetxt(f, chunk, fmt="%d")
    print("Large data file created successfully.")

# ----------------------------------------------------
# 2. ASSIGN SUBSEQUENT ROWS TO FIRST ROW ELEMENTS
# ----------------------------------------------------

def assign_rows_to_first_row(matrix):
    first_row = matrix[0]
    result = {}
    for i, val in enumerate(first_row):
        result[val] = matrix[1:, i]
    return result

# ----------------------------------------------------
# 3. GROUP SIMILAR ELEMENTS IN MATRIX
# ----------------------------------------------------

def group_similar_elements(matrix):
    groups = defaultdict(list)
    for row in matrix:
        for val in row:
            groups[val].append(val)
    return dict(groups)

# ----------------------------------------------------
# 4. ADD AND SUBTRACT MATRICES
# ----------------------------------------------------

def add_and_subtract_matrices(A, B):
    A = np.array(A)
    B = np.array(B)
    addition = A + B
    subtraction = A - B
    return addition, subtraction

# ----------------------------------------------------
# 5. CREATE n x n MATRIX WHERE OPPOSITE CORNER SUM IS EVEN
# ----------------------------------------------------

def create_even_corner_matrix(n):
    matrix = np.zeros((n, n), dtype=int)
    for i in range(n):
        for j in range(n):
            matrix[i][j] = (i + j) * 2   # ensures even sums
    return matrix

# ----------------------------------------------------
# 6. ROW-WISE ELEMENT ADDITION IN TUPLE MATRIX
# ----------------------------------------------------

def row_wise_tuple_addition(tuple_matrix):
    return tuple(sum(row) for row in tuple_matrix)

# ----------------------------------------------------
# SAMPLE EXECUTION (SMALL DATA FOR DEMO)
# ----------------------------------------------------

if __name__ == "__main__":

    # 1. Large file generation (comment if not required to run)
    # create_large_data_file()

    # Sample matrix
    mat = np.array([
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ])

    print("\n2. Assign rows to first row elements:")
    print(assign_rows_to_first_row(mat))

    print("\n3. Group similar elements:")
    print(group_similar_elements(mat))

    A = [[1, 2], [3, 4]]
    B = [[5, 6], [7, 8]]

    add, sub = add_and_subtract_matrices(A, B)
    print("\n4. Matrix Addition:\n", add)
    print("Matrix Subtraction:\n", sub)

    print("\n5. Even corner matrix (n=4):")
    print(create_even_corner_matrix(4))

    tuple_mat = (
        (1, 2, 3),
        (4, 5, 6),
        (7, 8, 9)
    )

    print("\n6. Row-wise tuple addition:")
    print(row_wise_tuple_addition(tuple_mat))


2. Assign rows to first row elements:
{np.int64(1): array([4, 7]), np.int64(2): array([5, 8]), np.int64(3): array([6, 9])}

3. Group similar elements:
{np.int64(1): [np.int64(1)], np.int64(2): [np.int64(2)], np.int64(3): [np.int64(3)], np.int64(4): [np.int64(4)], np.int64(5): [np.int64(5)], np.int64(6): [np.int64(6)], np.int64(7): [np.int64(7)], np.int64(8): [np.int64(8)], np.int64(9): [np.int64(9)]}

4. Matrix Addition:
 [[ 6  8]
 [10 12]]
Matrix Subtraction:
 [[-4 -4]
 [-4 -4]]

5. Even corner matrix (n=4):
[[ 0  2  4  6]
 [ 2  4  6  8]
 [ 4  6  8 10]
 [ 6  8 10 12]]

6. Row-wise tuple addition:
(6, 15, 24)
